name: "qwen3-4b-thinking-2507"
adapter: "lmstudio"
model_id: "qwen/qwen3-4b-thinking-2507"
postprocess: "hooks.qwen_strip_think:postprocess" # strips <think> blocks returned by Qwen Thinking models
runtime:
  temperature: 0.7
  max_tokens: -1
