name: "MVP Basic"
description: "Tiny smoke-test tournament: 2 models x 1 exploit"
models:
  - "gpt-oss-20b"
  - "gemma-3-27b"
exploits:
  - "secret_extraction"
settings:
  max_turns: 10
  repetitions: 2
  output_dir: "results/mvp_basic"
  privacy_tier: "private"
