name: "MVP Basic"
description: "Tiny smoke-test tournament: 2 models x 1 exploit"
models:
  - "gemma-3-27b"
  - "qwen3-4b-thinking-2507"
  # - "deepseek-r1-0528-qwen3-8b"
exploits:
  - "secret_extraction"
settings:
  max_turns: 10
  repetitions: 2
  output_dir: "results/mvp_basic"
  privacy_tier: "private"
