name: "MVP Basic"
description: "Tiny smoke-test tournament: 2 models x 1 exploit"
models:
  - "qwen3-4b-thinking-2507"
  - "llama-3.3-70b"
exploits:
  - "secret_extraction"
settings:
  max_turns: 10
  repetitions: 2
  output_dir: "results/mvp_basic"
  privacy_tier: "private"
