name: "Quick Test"
description: "Single match run for development/debugging"
models:
  - "llama-3.3-70b"
exploits:
  - "secret_extraction"
settings:
  max_turns: 4
  repetitions: 1
  output_dir: "results/quick_test"
  privacy_tier: "private"
